---
- name: Install dependencies
  hosts: "nginx"
  become: yes
  pre_tasks:
    - name: Configure MariaDB Repository
      yum_repository:
        name: mariadb
        description: MariaDB
        baseurl: http://yum.mariadb.org/10.6/centos7-amd64
        gpgkey: https://yum.mariadb.org/RPM-GPG-KEY-MariaDB
        gpgcheck: true
        state: present
      when: ansible_os_family == "RedHat"

    - name: Override variables for MySQL (RedHat).
      set_fact:
        mysql_daemon: mariadb
        mysql_packages:
          - mariadb
          - mariadb-server
          - MySQL-python
        mysql_syslog_tag: mariadb
        mysql_pid_file: /var/lib/mysql/mariadb.pid
      when: ansible_os_family == "RedHat"
  roles:
    - geerlingguy.git
    - name: geerlingguy.repo-remi
      when: ansible_os_family == 'RedHat'
    - { role: geerlingguy.nginx, ssl: false }
    - geerlingguy.php-versions
    - geerlingguy.php
    - geerlingguy.mysql
    - geerlingguy.certbot
    - eaudeweb.nginx_snippets
    - { role: geerlingguy.nginx, ssl: true }
    - geerlingguy.github-users
  vars:
    nginx_vhost_template: "{{ playbook_dir }}/templates/nginx_vhost.j2"

    mysql_pid_file: /var/lib/mysql/mariadb.pid
    mysql_slow_query_log_enabled: false
    mysql_slow_query_log_file: "/var/log/mariadb/slow-query.log"
    mysql_myisam_sort_buffer_size: "16M"
    mysql_table_open_cache: "16384"
    mysql_thread_cache_size: "128"
    mysql_max_connections: "256"
    mysql_key_buffer_size: "64M"
    mysql_sort_buffer_size: "3M"
    mysql_read_buffer_size: "2M"
    mysql_read_rnd_buffer_size: "32M"
    mysql_join_buffer_size: "8M"
    mysql_tmp_table_size: "256M"
    mysql_max_heap_table_size: "256M"
    mysql_query_cache_size: "32M"
    mysql_query_cache_limit: "6M"
    mysql_max_allowed_packet: "216M"
    mysql_innodb_file_per_table: "1"
    mysql_innodb_log_file_size: "128M"
    mysql_innodb_log_buffer_size: "4M"
    mysql_innodb_buffer_pool_size: "256M"
    mysql_innodb_lock_wait_timeout: "3600"

    php_realpath_cache_size: "4096k"
    php_expose_php: "Off"
    php_fpm_pool_user: nginx
    php_fpm_pool_group: nginx
    php_memory_limit: "512M"
    php_max_execution_time: "90"
    php_max_input_vars: "10000"
    php_upload_max_filesize: "256M"
    php_enable_php_fpm: true
    php_opcache_enable: true
    php_enable_webserver: false
    php_error_log: "syslog"
    php_post_max_size: "256M"
    php_date_timezone: "UTC"

    certbot_admin_email: stefan.butura@eaudeweb.ro
    certbot_create_if_missing: true
    certbot_create_method: webroot
    certbot_webroot: /usr/share/nginx/html/letsencrypt
    certbot_create_standalone_stop_services: false

    php_packages:
      - php-bcmath
      - php-bz2
      - php-cli
      - php-curl
      - php-common
      - php-devel
      - php-fpm
      - php-gd
      - php-intl
      - php-mbstring
      - php-mcrypt
      - php-mysqlnd
      - php-opcache
      - php-pdo
      - php-pecl-apcu
      - php-xml
      - php-zip
  vars_files:
    - "{{ playbook_dir }}/host_vars/{{ inventory_hostname }}/mysql_vars.yml"
    - "{{ playbook_dir }}/host_vars/{{ inventory_hostname }}/php_vars.yml"
    - "{{ playbook_dir }}/host_vars/{{ inventory_hostname }}/nginx_vars.yml"
    - "{{ playbook_dir }}/host_vars/{{ inventory_hostname }}/certbot_vars.yml"
    - "{{ playbook_dir }}/host_vars/{{ inventory_hostname }}/users_vars.yml"

- name: Install composer
  hosts: "nginx"
  roles:
    - geerlingguy.composer

- name: Make users passwordless for sudo in group wheel
  hosts: nginx
  tasks:
    - lineinfile:
        path: /etc/sudoers
        state: present
        regexp: '^%wheel'
        line: '%wheel ALL=(ALL) NOPASSWD: ALL'
        validate: 'visudo -cf %s'

- name: Make a certain version of PHP the default one
  hosts: nginx
  tasks:
    - alternatives:
        name: php
        link: /usr/bin/php
        path: "{{ php_executable }}"
        priority: 10
  vars_files:
    - "{{ playbook_dir }}/host_vars/{{ inventory_hostname }}/php_vars.yml"
