# From Ansible Galaxy
- src: geerlingguy.certbot
- src: geerlingguy.composer
- src: geerlingguy.git
- src: geerlingguy.nginx
- src: geerlingguy.php
- src: geerlingguy.php-versions
- src: geerlingguy.repo-remi
- src: geerlingguy.mysql
- src: geerlingguy.github-users
