# From Ansible Galaxy
- src: geerlingguy.certbot
- src: geerlingguy.composer
- src: geerlingguy.git
- src: geerlingguy.nginx
- src: geerlingguy.php
- src: geerlingguy.php-versions
- src: geerlingguy.repo-remi

- src: https://github.com/stefanbutura/ansible-role-mysql.git
  version: master
  name: geerlingguy.mysql

- src: https://github.com/stefanbutura/ansible-role-nginx.git
  version: master
  name: stefanbutura.nginx
